import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/containers/header";
import Footer from "@/components/containers/footer";
import { TailwindIndicator } from "@/components/ui/tailwindIndicator";
import BackgroundBanner from "@/components/ui/bg";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Penta",
  description: "Generated by nextbase",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={
          (inter.className,
          "bg-white text-black antialiased dark:bg-gray-950 dark:text-white min-h-screen")
        }
      >
        <Header />
        <BackgroundBanner />
        <TailwindIndicator />
        {children}
        <Footer />
      </body>
    </html>
  );
}
