import type { Metadata } from "next";
import { GeistSans } from "geist/font/sans";
import "./globals.css";
import Header from "@/components/containers/header";
import Footer from "@/components/containers/footer";
import { TailwindIndicator } from "@/components/ui/tailwindIndicator";
import BackgroundBanner from "@/components/ui/bg";


export const metadata: Metadata = {
  title: "duex",
  description: "Generated by nextbase",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body className={GeistSans.className}>
        <Header />
        <BackgroundBanner />
        <TailwindIndicator />
        {children}
        <Footer />
      </body>
    </html>
  );
}
