import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/containers/header";
import Footer from "@/components/containers/footer";
import { TailwindIndicator } from "@/components/ui/tailwindIndicator";

export const metadata: Metadata = {
  title: "Heptagon | Nextbase Template",
  description: "Generated by NextBase Team",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased transition-all min-h-screen">
        {children}
        <Footer />
        <TailwindIndicator />
      </body>
    </html>
  );
}
